# Generated by Django 6.0.4 on 2026-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для курса', null=True, upload_to='courses/previews/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение для урока', null=True, upload_to='lessons/previews/', verbose_name='Превью')),
                ('video_url', models.URLField(help_text='Введите ссылку на видеоурок', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['id'],
            },
        ),
    ]
